get-teams-in-league:
    path: /leagues/{leagueId}/teams
    defaults:
        _controller: football-api.controller.teams::getTeamsInLeague
    methods:  [GET]

create-team:
    path: /leagues/{leagueId}/teams
    defaults:
        _controller: football-api.controller.teams::createTeam
    methods:  [POST]
