FootballApi\Domain\League\League:
  type: entity
  table: leagues
  repositoryClass: FootballApi\Infrastructure\Persistence\Doctrine\LeagueRepository
  uniqueConstraints:
    name_idx:
      columns: [ name ]
  id:
    id:
      type: guid
  fields:
    name:
      type: string
      length: 255
      nullable: false
  oneToMany:
    teams:
      targetEntity: FootballApi\Domain\Team\Team
      mappedBy: league
      cascade: ["persist", "merge", "remove"]
      onDelete: CASCADE